name: Build package and publish the GitHub release
author: Oleksandr Nikolaiev
permissions:
  contents: write
  pull-requests: write
  workflows: write
inputs:
  actor:
    description: The GitHub actor running the action
    required: false
    default: ${{ github.actor }}
  token:
    description: The GitHub token running the action
    required: false
    default: ${{ github.token }}
  settingsJson:
    description: Settings from repository in compressed Json format
    required: false
    default: ''
  secretsJson:
    description: Secrets from repository in compressed Json format
    required: false
    default: ''
  artifactsPath:
    description: Secrets from repository in compressed Json format
    required: false
    default: ''
  type:
    description: Repo type
    required: true
    default: 'FSCM'
runs:
  using: composite
  steps:
    - name: run
      shell: PowerShell
      env:
        _actor: ${{ inputs.actor }}
        _type: ${{ inputs.type }}
        _token: ${{ inputs.token }}
        _settingsJson: ${{ inputs.settingsJson }}
        _artifactsPath: ${{ inputs.artifactsPath }}
        _secretsJson: ${{ inputs.secretsJson }}
      run: try { ${{ github.action_path }}/PublishRelease.ps1 -type $ENV:_type -artifactsPath $ENV:_artifactsPath -actor $ENV:_actor -token $ENV:_token -settingsJson $ENV:_settingsJson -secretsJson $ENV:_secretsJson  } catch { Write-Host "::Error::Unexpected error when running action ($($_.Exception.Message.Replace("`r",'').Replace("`n",' ')))"; exit 1 }
branding:
  icon: terminal
  color: blue
