name: Post process action. Cleanup.
author: Oleksandr Nikolaiev
inputs:
  token:
    description: The GitHub token running the action
    required: false
    default: ${{ github.token }}
  remove_current:
    description: The GitHub actor running the action
    required: false
  settingsJson:
    description: Settings from repository in compressed Json format
    required: false
    default: ''
  secretsJson:
    description: Secrets from repository in compressed Json format
    required: false
    default: '{"insiderSasToken":"","licenseFileUrl":"","codeSignDigiCertUrl":"","codeSignDigiCertPw":""}'

runs:
  using: composite
  steps:
    - run: 
            try { 
                if('${{ inputs.remove_current }}' -eq 'true')
                {
                    ${{ github.action_path }}/WorkflowPostProcess.ps1 -token '${{ inputs.token }}' -settingsJson '${{ inputs.settingsJson }}' -secretsJson '${{ inputs.secretsJson }}' -remove:$True
                }
                else
                {
                    ${{ github.action_path }}/WorkflowPostProcess.ps1 -token '${{ inputs.token }}' -settingsJson '${{ inputs.settingsJson }}' -secretsJson '${{ inputs.secretsJson }}'
                }
           } catch { 
                Write-Host "::Error::Unexpected error when running action ($($_.Exception.Message))"; exit 1 
           }
      shell: PowerShell
branding:
  icon: terminal
  color: blue
