name: PowerShell script
author: Oleksandr Nikolaiev
permissions:
  contents: write
  pull-requests: write
  workflows: write
inputs:
  actor:
    description: The GitHub actor running the action
    required: false
    default: ${{ github.actor }}
  token:
    description: The GitHub token running the action
    required: false
    default: ${{ github.token }}
  templateUrl:
    description: URL of the template repository (default is the template repository used to create the repository)
    required: false
    default: ''
  templateBranch:
    description: Branch in template repository to use for the update (default is the default branch)
    required: false
    default: ''
  settingsJson:
    description: Settings from repository in compressed Json format
    required: false
    default: ''
  secretsJson:
    description: Secrets from repository in compressed Json format
    required: false
    default: ''
  update:
    description: Set this input to Y in order to update AL-Go System Files if needed
    required: false
    default: 'N'
  directCommit:
    description: Direct Commit (Y/N)
    required: false
    default: 'N'
  type:
    description: Repo type
    required: true
    default: 'FSCM'
runs:
  using: composite
  steps:
    - name: run
      shell: PowerShell
      env:
        _actor: ${{ inputs.actor }}
        _type: ${{ inputs.type }}
        _token: ${{ inputs.token }}
        _templateUrl: ${{ inputs.templateUrl }}
        _templateBranch: ${{ inputs.templateBranch }}
        _settingsJson: ${{ inputs.settingsJson }}
        _secretsJson: ${{ inputs.secretsJson }}
        _update: ${{ inputs.update }}
        _directCommit: ${{ inputs.directCommit }}
      run: try { ${{ github.action_path }}/CheckForUpdates.ps1 -type $ENV:_type -actor $ENV:_actor -token $ENV:_token -settingsJson $ENV:_settingsJson -secretsJson $ENV:_secretsJson -templateUrl $ENV:_templateUrl -templateBranch $ENV:_templateBranch -update ($ENV:_update -eq 'Y') -directCommit ($ENV:_directCommit -eq 'Y') } catch { Write-Host "::Error::Unexpected error when running action ($($_.Exception.Message.Replace("`r",'').Replace("`n",' ')))"; exit 1 }
branding:
  icon: terminal
  color: blue
