name: Restore Nugets from FSC storage
author: Florian Hopfner
inputs:
  version:
    description: The Dynamics Application Version
    required: true
runs:
  using: composite
  steps:
    - run: try { ${{ github.action_path }}/RestoreFSCNuget.ps1 -DynamicsVersion '${{ inputs.version }}' } catch { Write-Host "::Error::Unexpected error when running action ($($_.Exception.Message))"; exit 1 }
      id: restorefscnuget
      shell: PowerShell